version: "2"

services:
  agendav:
    image: agendav:dev
    container_name: agendavdev
    environment:
      - AGENDAV_SERVER_NAME=127.0.0.1
      - AGENDAV_TITLE=Welcome to Example Agendav Server
      - AGENDAV_FOOTER=Hosted by Example Company
      - AGENDAV_ENC_KEY=my_encrypt10n_k3y
      - AGENDAV_CALDAV_SERVER=https://baikal.example.com/cal.php
      - AGENDAV_CALDAV_PUBLIC_URL=https://baikal.example.com
      - AGENDAV_TIMEZONE=UTC
      - AGENDAV_LANG=en
      - AGENDAV_LOG_DIR=/tmp/
    ports:
      - "80:8080"
